language: python
python:
  - 2.7
  - 3.6
notifications:
  email: false

# Install requirements and pytest
install:
  - pip install -r requirements.txt
  - pip install pytest

# Run test
script:
  - pytest tests
